[package]
name = "tbr"
description = "Terminal ebook reader"
authors = ["zang.loo"]
version = "2.0.4"
homepage = "https://github.com/zangloo/tbr"
repository = "https://github.com/zangloo/tbr.git"
keywords = ["terminal", "ebook"]
license = "GPL-2.0-only"
readme = "README.md"
categories = ["command-line-utilities"]
edition = "2021"

[features]
default = ["gui"]
gui = ["i18n"]
i18n = []

[target.'cfg(windows)'.dependencies]
cursive = { version = "0.17", default-features = false, features = ["crossterm-backend", "toml"] }

[target.'cfg(unix)'.dependencies]
cursive = { version = "0.17", features = ["toml"] }

[dependencies]
anyhow = "1.0"
clap = { version = "3.0", features = ["derive"] }
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
toml = "0.5"
rust-embed = "6.3"
xmltree = "0.10"
unicode-width = "0.1"
regex = "1.5"
chardetng = "0.1"
encoding_rs = "0.8"
zip = "0.5"
lexical-sort = "0.3"
strip_bom = "1.0"

markup5ever = "0.10"
scraper = "0.12"
cssparser = "0.29"
parcel_css = "1.0.0-alpha"
ego-tree = "0.6"

fluent = "0.16"
unic-langid = "0.9"
sys-locale = "0.2"

eframe = "0.18"
egui = "0.18"
egui_extras = { version = "0.18", features = ["svg"] }
rfd = "0.8"
image = "0.24"
