[package]
name = "tbr"
description = "Terminal ebook reader"
authors = ["zang.loo"]
version = "1.0.4"
homepage = "https://github.com/zangloo/tbr"
repository = "https://github.com/zangloo/tbr.git"
keywords = ["terminal", "ebook"]
license = "GPL-2.0-only"
readme = "README.md"
categories = ["command-line-utilities"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.13", features = ["derive"] }
dirs = "4.0.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_derive = "1.0.136"
toml = "0.5.8"
rust-embed = "6.3.0"
epub = "1.2.3"
html5ever = "0.25.1"
markup5ever = "0.10.1"
markup5ever_rcdom = "0.1.0"
cursive = { version = "0.17.0", features = ["toml"] }
unicode-width = "0.1.9"
regex = "1.5.4"
chardetng = "0.1.17"
encoding_rs = "0.8.30"
zip = "0.5.13"
lexical-sort = "0.3.1"
